server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Esta línea es vital para react-router-dom:
        # Si no encuentra la ruta física, redirige a index.html
        try_files $uri $uri/ /index.html;
    }

    # Optimización opcional para errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
