spring:
  application:
    name: subsonic-usuarios

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/subsonic_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:subsonicfestivaloficial@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email


# Configuración JWT externalizada
jwt:
  secret: ${JWT_SECRET}
  expiration: 36000000  # 10 horas en milisegundos



# ==========================================
# CONFIGURACIÓN DE LA API DE SPOTIFY
# ==========================================

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID:AQUI_PONDRAS_TU_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET:AQUI_PONDRAS_TU_CLIENT_SECRET}
  refresh:
    token: ${SPOTIFY_REFRESH_TOKEN:AQUI_PONDRAS_EL_REFRESH_TOKEN}
  playlist:
    id: "3mSEthCx9XauDTZMQ0AV67"


paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  base-url: ${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}

