# ==========================================
# 1. CONFIGURACIÓN COMÚN (Todos los entornos)
# ==========================================
spring:
  application:
    name: subsonic-usuarios

  mail:
    host: smtp.gmail.com
    port: 587
    username: subsonicfestivaloficial@gmail.com
    password: hdjzsevpafemnvuh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1066356702795-ho4rfgnn52465fmscesjkjntb2g7ltqq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

# Configuración JWT externalizada
jwt:
  secret: tu_llave_secreta_super_larga_para_el_festival_subsonic
  expiration: 36000000  # 10 horas en milisegundos

# ==========================================
# CONFIGURACIÓN DE LA API DE SPOTIFY
# ==========================================

spotify:
  client:
    id: "AQUI_PONDRAS_TU_CLIENT_ID_MAÑANA"
    secret: "AQUI_PONDRAS_TU_CLIENT_SECRET_MAÑANA"
  refresh:
    token: "AQUI_PONDRAS_EL_REFRESH_TOKEN_MAÑANA"
  playlist:
    id: "3mSEthCx9XauDTZMQ0AV67"

paypal:
  client-id: AflOCYdbF2GcWXzhclwsNUscftIddp_kUIOjLAVd7O73EC9GOxTFOuOlHUss_3H-SstaAOcsSgoCRdjh
  client-secret: EDZkqZEDrj_ZcS7b2wv6oM21rZizY4r9svXpAOgdH5aqGehUrZdmgEsoBIZLns8J80vdhMFIiI5ov7Sr
  base-url: https://api-m.sandbox.paypal.com

---
  # ==========================================
  # 2. PERFIL LOCAL (Para programar en tu PC)
  # ==========================================

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subsonic_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: http://localhost:5173














